SELECT 
    CHILD.ITEM_ID, 
    CHILD.ITEM_NAME, 
    CHILD.RARITY
FROM ITEM_TREE TREE
JOIN ITEM_INFO PARENT ON TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
JOIN ITEM_INFO CHILD ON TREE.ITEM_ID = CHILD.ITEM_ID
WHERE PARENT.RARITY = 'RARE'
ORDER BY CHILD.ITEM_ID DESC;